name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: setup git config
        run: |
          git config user.name "Sadanand Pai"
          git config user.email "sadypai@gmail.com"

      - name: setup deployment
        run: |
          npm install
          npm run build
          git add docs -f
          git diff --staged --quiet || (git commit -m "build files - github action" && git push)
